lib/yak/web/router.ex
defmodule Yak.Web.Router do
  use Yak.Web, :router
  use Plug.ErrorHandler

  defp handle_errors(conn, %{kind: kind, reason: reason, stack: stacktrace}) do
    Rollbax.report(kind, reason, stacktrace)
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Yak.Web do
    pipe_through :browser # Use the default browser stack

    get "/", JobController, :index
    get "/ponuky", JobController, :index
    post "/ponuky", JobController, :create

    put "/ponuka/:token", JobController, :update
    patch "/ponuka/:token", JobController, :update

    get "/ponuka/nova", JobController, :new
    get "/ponuka/:token/nahlad", JobController, :preview 
    get "/ponuka/:permalink", JobController, :show

    get "/ponuka/:token/upravit", JobController, :edit
    patch "/ponuka/:token/potvrdit", JobController, :confirm

    get "/kategoria/:permalink", CategoryController, :show

    get "/hladaj/:term", SearchController, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", Yak.Web do
  #   pipe_through :api
  # end
end

lib/yak/web/controllers/category_controller.ex
defmodule Yak.Web.CategoryController do
  
  use Yak.Web, :controller

  alias Yak.Board

  def show(conn, %{"permalink" => permalink}) do
    category = Board.get_category_with_jobs(permalink)
    render conn, :show, category: category
  end
end

lib/yak/web/controllers/job_controller.ex
defmodule Yak.Web.JobController do
  
  use Yak.Web, :controller

  alias Yak.Board

  def index(conn, _assigns) do
    categories = Board.list_categories_public    
    render(conn, :index, categories: categories)
  end

  def show(conn, %{"permalink" => permalink}) do
    job = Board.get_job!(permalink)
    |> Board.preload_category()
    
    Toniq.enqueue(Yak.Worker.ViewCount, job)

    render conn, :show, job: job
  end

  def new(conn, _assigns) do
    render(conn, :new, 
      changeset: Board.change_job(%Board.Job{}),
      categories: Board.list_categories())
  end

  def create(conn, %{"job" => job_params}) do
    case Board.create_job(job_params) do
      {:ok, job} ->    
        redirect conn, to: job_path(conn, :preview, job.token)
      {:error, %Ecto.Changeset{} = changeset} ->
        render conn, :new, changeset: changeset, categories: Board.list_categories()
    end
  end

  def edit(conn, %{"token" => token}) do
    job = Board.get_job_by! token: token

    render(conn, :edit, 
      changeset: Board.change_job(job),
      categories: Board.Category.Store.list())
  end

  def update(conn, %{"token" => token, "job" => job_params}) do
    job = Board.get_job_by!(token: token)

    case Board.update_job(job, job_params) do
      {:ok, job} ->
        Toniq.enqueue(Yak.Worker.ChangeStatus, job: job, status: :updated)

        redirect conn, to: job_path(conn, :preview, job.token)
      {:error, %Ecto.Changeset{} = changeset} ->
        render conn, :edit, changeset: changeset, categories: Board.Category.Store.list()
    end
  end

  def preview(conn, %{"token" => token}) do
    job = Board.get_job_by!(token: token)
    render conn, :preview, job: job
  end

  def confirm(conn, %{"token" => token}) do
    job = Board.get_job_by!(token: token)
    
    # Toniq.enqueue(Yak.Worker.Notification, template: :confirmation, job: job, conn: conn)
    # Toniq.enqueue(Yak.Worker.Index, conn: conn, job: job)
    Toniq.enqueue(Yak.Worker.ChangeStatus, job: job, status: :pending)

    redirect conn, to: job_path(conn, :index), notice: "Ponuka bola vytvorená"
  end
end

lib/yak/web/controllers/page_controller.ex
defmodule Yak.Web.PageController do
  use Yak.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

lib/yak/web/views/category_view.ex
defmodule Yak.Web.CategoryView do
  use Yak.Web, :view
  require Logger

  def title("show.html", assigns) do
    assigns.category.name
  end

  def title(_, _assigns), do: ""
end

lib/yak/web/views/error_view.ex
defmodule Yak.Web.ErrorView do
  use Yak.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

lib/yak/web/views/job_view.ex
defmodule Yak.Web.JobView do
  use Yak.Web, :view

  def title("show.html", assigns) do
    assigns.job.title <> " - " <> assigns.job.company
  end

  def title("new.html", _assigns) do
    "Nová ponuka práce"
  end

  def title("edit.html", _assigns) do
    "Úprava ponuky práce"
  end

  def title("preview.html", _assigns) do
    "Náhľad ponuky práce"
  end

  def title(_, _assigns), do: "Všetky ponuky"
end

lib/yak/web/views/layout_view.ex
defmodule Yak.Web.LayoutView do
  use Yak.Web, :view
end

lib/yak/web/views/page_view.ex
defmodule Yak.Web.PageView do
  use Yak.Web, :view

  def title(_, _assigns), do: "Ponuky"
end

lib/yak/web/templates/category/show.html.eex
<section class="category">
  <div class="row row--middle category__row">
    <h2 class="category__header"><%= @category.name %></h2>
    
    <div class="category__job-count">
      <%= bend(Enum.count(@category.jobs), %{one: "ponuka", twotofor: "ponuky", more: "ponúk"}) %>
    </div>
  </div>

  <ul class="list--no-style">
    <%= for job <- @category.jobs do %>
      <%= link to: job_path(@conn, :show, job), class: "link job--link" do %>
      <li class="job">
        <div class="job__title <%= new_job?(job) %>"><%= job.title %></div>

        <div class="job__info">
          <div class="column">
            <span class="job__company"><%= job.company %></span>,&nbsp;
            <span class="job__location"><%= job.location %></span>
          </div>
          <div class="column">
            <span class="job__date"><%= Timex.format! job.inserted_at, "{D} {Mshort}" %></span>
          </div>
        </div>
      </li>
      <% end %> 
    <% end %>
    <%= if @category.jobs == [] do %>
      <li class="nothing">
        Zatiaľ tu nič nie je 😞
      </li>
    <% end %>
  </ul>
</section>

lib/yak/web/templates/job/edit.html.eex
<h2>Upravenie ponuky</h2>

<%= render "form.html", 
    changeset: @changeset,
    action: job_path(@conn, :update, @changeset.data.token),
    categories: @categories,
    
    button_text: "Upraviť ponuku a pokračovať na náhľad",
    errors: @changeset.errors %>

lib/yak/web/templates/job/form.html.eex
<%= form_for @changeset, @action, [multipart: true], fn f -> %>
  <%= if @changeset.action do %>
      <div class="alert alert-danger">
        <p>Ups! Niečo sa pokazilo. Prosím, skontroluj všetky políčka formuláru.</p>
      </div>
  <% end %>

  <section>
    <h3>Informácie o pozícii</h3>

    <div class="form-group">
      <%= label f, :title, "Názov pozície", class: "control-label" %>
      <div style="width: 100%">
        <%= text_input f, :title, class: "control-label" %>
        <%= error_tag f, :title, %{"can't be blank" => "Prosím vyplň názov pozície"} %>  
        <div class="tip">"PHP programátor" alebo "Senior manažér"</div>
      </div>
    </div>

    <div class="form-group form-group--vcenter">
      <div style="display: -webkit-flex;display: -ms-flex;display: flex;">
        <label class="control-label">Kategória</label>
        <ul class="list--no-style">
          <%= for category <- @categories do %>
            <li><label>
            <%= radio_button f, :category_id, category.id %>
            <span><%= category.name %></span></label></li>
          <% end %>
        </ul>
      </div>
      <%= error_tag f, :category_id, %{"can't be blank" => "Prosím zvoľ kategóriu"} %>
    </div>

    <div class="form-group">
      <%= label f, :location, "Miesto práce", class: "control-label" %>
      <div style="width: 100%">
        <%= text_input f, :location, class: "control-label" %>
        <%= error_tag f, :location, %{"can't be blank" => "Prosím vyplň miesto práce"} %>
        <div class="tip">Iba mesto - Žilina, Bratislava...</div>
      </div>
    </div>

    <div class="form-group form-group--column">
      <div class="input-header">
        <%= label f, :description, "Popis pozície", class: "control-label control-label--padded" %>
        <%= error_tag f, :description, %{"can't be blank" => "Prosím, vyplňte popis pozície"} %>
      </div>
      <%= hidden_input f, :description %>
      <%= hidden_input f, :description_formatted %>
      <div id="description-container"></div>
    </div>

    <div class="form-group instructions form-group--column">
      <div class="input-header">
        <%= label f, :instructions, "Ako vás uchádzači môžu kontaktovať ak majú záujem?", class: "control-label control-label--padded" %>
        <%= error_tag f, :instructions, %{"can't be blank" => "Prosím vyplň ako vás uchádzači môžu kontaktovať"}, "error--margin-vertical" %>
      </div>
      <%= text_input f, :instructions, class: "full-width" %>
      <div class="tip">Napríklad "Pošlite email s priloženým CV na..."</div>
    </div>
  </section>

  <section>
    <h3>Informácie o firme</h3>

    <div class="form-group">
      <%= label f, :company, "Meno firmy", class: "control-label control-label--company" %>
      <%= text_input f, :company %>
      <%= error_tag f, :company, %{"can't be blank" => "Prosím zadaj meno firmy"} %>
    </div>

    <div class="form-group">
      <%= label f, :logo, class: "control-label control-label--company" %>
      <%= file_input f, :logo %>
    </div>

    <div class="form-group">
      <%= if @changeset.data.logo do %>
        <label class="control-label control-label--company">Aktuálne logo</label>
        <img src='<%= "https://yak-dev.s3-eu-central-1.amazonaws.com" <> @changeset.data.logo %>' alt="">
      <% end %>
    </div>

    <div class="form-group">
      <%= label f, :url, "Web firmy", class: "control-label control-label--company" %>
      <%= text_input f, :url %>
    </div>

    <div class="form-group">
      <%= label f, :email, "Email zamestnanca", class: "control-label control-label--company" %>
      <%= text_input f, :email %>
      <%= error_tag f, :email, %{"can't be blank" => "Prosím vyplň emailovú adresu"} %>
    </div>

    <div class="form-group">
      <%= if @button_text do %>
        <%= submit @button_text, class: "btn btn--primary" %>
      <% else %>
        <%= submit "Uložiť", class: "btn btn--primary" %>
      <% end %>
    </div>
  </section>
<% end %>

lib/yak/web/templates/job/index.html.eex
<div class="motto">
  Hľadáš miesto v IT? Nehľadaj, ale vyberaj.
</div>

<%= for category <- @categories do %>
  <%= if category.job_count > 0 do %>
    <section class="category">
      <h2 class="category__header category__header--home"><%= category.name %></h2>

      <ul class="list--no-style">
        <%= for job <- category.jobs do %>
          <%= link to: job_path(@conn, :show, job), class: "link job--link" do %>
          <li class="job">
            <div class="job__title <%= new_job?(job) %>">
              <%= job.title %>
            </div>
            
            <div class="job__info">
              <div class="column">
                <span class="job__company"><%= job.company %></span>,&nbsp;
                <span class="job__location"><%= job.location %></span>
              </div>
              <div class="column">
                <span class="job__date"><%= Timex.format! job.inserted_at, "{D} {Mshort}" %></span>
              </div>
            </div>
          </li>
          <% end %> 
        <% end %>

        <%= if category.job_count > Enum.count(category.jobs) do %>
          <li class="category--more">
            <%= link to: category_path(@conn, :show, category.permalink), class: "link" do %>
              <%= bend(category.job_count - Enum.count(category.jobs), %{one: "ďalšia ponuka", twotofor: "ďalšie ponuky", more: "ďalších ponúk"}) %>
              v <%= category.lokal %> →
            <% end %>
          </li>
        <% end %>
      </ul>
    </section>
  <% end %>
<% end %>

lib/yak/web/templates/job/job.html.eex
<article class="job">

  <header>
    <div class="meta">
      <h1><%= @job.title %></h1>
      <time datetime="<%= @job.inserted_at %>">Pridané <%= Timex.format! @job.inserted_at, "{D}.{M}.{YYYY}" %></time>
      
      <div class="job--company">
        <%= @job.company %>
      </div>
      <div class="job--location">
        <span>Miesto práce:</span> <%= @job.location %>
      </div>
    </div>

    <%= if not is_nil(@job.logo) do %>
    <img src='<%= "https://yak-dev.s3-eu-central-1.amazonaws.com" <> @job.logo %>' height="190px" alt="">
    <% end %>
  </header>

  <hr>

  <div class="content">
    <main>
      <div class="job__description">
        <%= raw(@job.description_formatted) %>
      </div>
    </main>

    <aside>
      <h3>Zdieľaj</h3>

      <div class="share--email">Pošli emailom</div>
      <div class="share--fb">Zdieľaj na facebook</div>
    </aside>
  </div>

  <hr>

  <footer>
    <h3>Ako sa prihlásiť na pozíciu</h3>
    <div class="instructions">
     <%= @job.instructions %>
    </div>
  </footer>
</article>

lib/yak/web/templates/job/new.html.eex
<h1>Pridanie novej ponuky</h1>

<%= render "form.html", 
    changeset: @changeset,
    action: job_path(@conn, :create),
    categories: @categories,
    
    button_text: "Pokračovať na náhľad ponuky",
    errors: @changeset.errors %>

lib/yak/web/templates/job/preview.html.eex
<h1>Náhľad ponuky</h1>

<div class="state">
Stav ponuky:

<%= if @job.status == :created do %>
  <div class="badge waiting">Neodoslaná</div>
<% end %>

<%= if @job.status == :waiting || @job.status == :updated do %>
  <div class="badge waiting">Čaká na potvrdenie</div>
<% end %>

<%= if @job.status == :approved do %>
  <div class="badge waiting">Uverejnená</div>
<% end %>
</div>

<p style="line-height: 1.4">Prejdite si prosím vašu ponuku a potvrďte ju alebo upravte. Po odoslaní vám bude doručený email na uvedenú emailovú adresu, kde bude link pomocou ktorého môžete ponuku stále upraviť.</p>

<hr>

<%= render "job.html", job: @job %>

<hr style="margin-bottom: 1.4em">

<%= if @job.status == :created or @job.status == :updated do %>
  <%= link "Všetko je v poriadku, odoslať", to: job_path(@conn, :confirm, @job.token), class: "btn btn--primary", method: :patch %>
<%= else %>
  <span class="btn btn--disabled">Ponuka už bola odoslaná na potvrdenie</span>
<% end %>

<%= link "Chcem ešte niečo upraviť", to: job_path(@conn, :edit, @job.token), class: "btn btn--primary", style: "margin-left: 0.33em" %>

lib/yak/web/templates/job/show.html.eex
<div class="row">
  <%= link "← Všetky ponuky", to: job_path(@conn, :index), class: "link" %>
  <%= link "Viac ponúk v #{@job.category.lokal} →", to: category_path(@conn, :show, @job.category.permalink), class: "link" %>
</div>

<%= render "job.html", job: @job %>

lib/yak/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Adam Gavlák">

    <title><%= @view_module.title(@view_template, assigns) %> – Yak</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/style.css") %>">
    <link rel="icon" href="<%= static_path(@conn, "/images/favicon.png") %>">
  </head>

  <body>
    <nav class="navigation" role="navigation" data-turbolinks-permanent>
      <div class="navigation__container">
        <div class="navigation__brand">
          <a href="/" class="navigation__link">
            <div class="h-row">
              <img src="<%= static_path(@conn, "/images/logo.svg") %>" alt="Logo Yaka" class="navigation__logo">
              <h1 class="navigation__title">Yak</h1>
            </div>
          </a>
        </div>
        
        <div class="navigation__right">
          <div class="navigation__search">

          </div>
          
          <ul class="navigation__list js-menu">
            <li class="navigation__item">
              <%= link "Všetky ponuky", to: job_path(@conn, :index), class: "navigation__link" %>
            </li>
            <li class="navigation__item navigation__item--dropdown">
              <span class="dropdown__text">Kategórie</span>
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="10" viewBox="0 0 16 10" fill="none" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="chevron--down">
                  <polyline points="2 2 8 8 14 2"/>
              </svg>

              <div class="dropdown">
                <ul class="dropdown__list">
                  <%= for category <- Board.Category.Store.list do %>
                  <li class="dropdown__item">
                    <%= link category.name, to: category_path(@conn, :show, category.permalink), class: "navigation__link" %>
                  </li>
                  <% end %>
                </ul>
              </div>
            </li>
            <li class="navigation__item">
              <%= link "Pridaj ponuku", to: job_path(@conn, :new), class: "button button--primary" %>
            </li>
          </ul>
          
          <div class="navigation__mobile">
            <span class="navigation__mobile--text">Menu</span>
            <button class="hamburger hamburger--elastic" type="button">
              <span class="hamburger-box">
                <span class="hamburger-inner"></span>
              </span>
            </button>
          </div>
        </div>
      </div>
    </nav>

    <main role="main" class="container">

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>

      <%= render @view_module, @view_template, assigns %>

    </main> <!-- /container -->

    <footer class="footer">
      <div class="footer__container">
        <div class="footer__column">
          <div class="footer__brand">
            <img src="<%= static_path(@conn, "/images/logo-transparent.svg") %>" alt="Logo" height="26">
            <h1 class="footer__title">Yak</h1>
          </div> 

          <div class="footer__copyright">©2017</div>
        </div>
        <div class="footer__column">
          <ul class="footer__list">
            <li class="footer__item">
              <h3 class="footer__heading">Kategórie</h3>
            </li>

            <%= for category <- Board.Category.Store.list do %>
            <li class="footer__item">
              <%= link category.name, to: category_path(@conn, :show, category.permalink), class: "footer__link" %>
            </li>
            <% end %>
          </ul>
        </div>
        <div class="footer__column">
          <ul class="footer__list">
            <li class="footer__item">
              <h3 class="footer__heading">O Yakovi</h3>
            </li>
            <li class="footer__item">
              <a href="#" class="footer__link">Čo je Yak?</a>
            </li>
            <li class="footer__item">
              <a href="#" class="footer__link">Kontakt</a>
            </li>
            <li class="footer__item">
              <a href="#" class="footer__link">FAQs</a>
            </li>
            <li class="footer__item">
              <a href="#" class="footer__link">Podmienky</a>
            </li>
          </ul>
        </div>
      </div>
    </footer>

    <script src="<%= static_path(@conn, "/js/app.js") %>" data-turbolinks-eval="false"></script>
  </body>
</html>

lib/yak/web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>